# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.cache/wt [current_project]
set_property parent.project_path G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/defines.v
set_property file_type "Verilog Header" [get_files G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/defines.v]
read_verilog -library xil_defaultlib {
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/ctrl.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/data_ram.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/div.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/ex.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/ex_mem.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/hilo_reg.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/id.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/id_ex.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/if_id.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/inst_rom.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/mem.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/mem_wb.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/openmips.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/openmips_min_sopc.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/pc_reg.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/regfile.v
  G:/vi_project/keshe/HelinCPU/CH9-5_CPU/CH9-5_CPU.srcs/sources_1/imports/Chapter9_1/openmips_min_sopc_tb.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top openmips_min_sopc_tb -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef openmips_min_sopc_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openmips_min_sopc_tb_utilization_synth.rpt -pb openmips_min_sopc_tb_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
